"""Staking reward accrual engine implementing Q64.64 fixed-point arithmetic."""

from packages.staking_reward_engine.pool import (
    MAX_U64,
    MAX_U128,
    Q64_FRACTIONAL_MASK,
    Q64_SCALE,
    Pool,
    PoolError,
    RewardCalcDivByZero,
    RewardCalcOverflow,
    RewardCalcUnderflow,
    RewardOverflow,
    RewardUnderflow,
    VulnerablePool,
    accrue_rewards,
    calculate_reward,
    checked_div,
    checked_div_q64_64,
    checked_mul,
    checked_mul_q64_64,
)
from packages.staking_reward_engine.verifier import StakingRewardFormalVerifier

__all__ = [
    "MAX_U64",
    "MAX_U128",
    "Q64_FRACTIONAL_MASK",
    "Q64_SCALE",
    "Pool",
    "PoolError",
    "RewardCalcDivByZero",
    "RewardCalcOverflow",
    "RewardCalcUnderflow",
    "RewardOverflow",
    "RewardUnderflow",
    "VulnerablePool",
    "accrue_rewards",
    "calculate_reward",
    "checked_div",
    "checked_div_q64_64",
    "checked_mul",
    "checked_mul_q64_64",
    "StakingRewardFormalVerifier",
]
