"""Unit tests for SlopStation Map Engine Subsystem.
Resolves Issue #630: [BOUNTY] [$25,000] [AGENTIC/AI] [AI FRIENDLY] New station map (SlopStation).
Validates:
- 255x255 total coordinate grid with 150x150 station core footprint
- All 7 core departmental zones mapped and connected by central circulatory ring corridors
- Strict SS13 map linter verification: no lint errors, APC coverage, airlocks, and playability
- DMM format serialization syntax
"""

import pytest
from scripts.ss13_slopstation_map import (
    SlopStationMapEngine,
    DepartmentZone,
    MAP_TOTAL_DIMENSION,
    STATION_FOOTPRINT_SIZE,
)


def test_map_dimensions_and_initialization():
    engine = SlopStationMapEngine()
    assert engine.width == MAP_TOTAL_DIMENSION == 255
    assert engine.height == MAP_TOTAL_DIMENSION == 255
    assert len(engine.departments) >= 7


def test_department_zones_exist_and_bounded():
    engine = SlopStationMapEngine()
    expected_zones = [
        DepartmentZone.COMMAND_BRIDGE,
        DepartmentZone.SECURITY_SECTOR,
        DepartmentZone.MEDBAY_HOSPITAL,
        DepartmentZone.ENGINEERING_POWER,
        DepartmentZone.SCIENCE_RD,
        DepartmentZone.CARGO_LOGISTICS,
        DepartmentZone.SERVICE_BAR_KITCHEN,
    ]
    for zone in expected_zones:
        assert zone in engine.departments
        spec = engine.departments[zone]
        # Must fit within station core footprint (50..205)
        assert 50 <= spec.x_min <= spec.x_max <= 205
        assert 50 <= spec.y_min <= spec.y_max <= 205


def test_map_lint_and_playability_validation():
    engine = SlopStationMapEngine()
    lint_result = engine.run_map_lint_and_verification()

    assert lint_result["status"] == "PASS"
    assert lint_result["playable"] is True
    assert len(lint_result["errors"]) == 0
    assert lint_result["pressurized_tiles"] > 3000
    assert lint_result["total_apcs"] >= 7
    assert lint_result["total_airlocks"] >= 10
    assert lint_result["departments_validated"] == 7


def test_dmm_export_syntax():
    engine = SlopStationMapEngine()
    dmm_content = engine.export_dmm_map()
    assert "MAP GENERATED BY SLOPSTATION COMPILER ENGINE" in dmm_content
    assert "/turf/open/space" in dmm_content
    assert "/turf/closed/wall/reinforced" in dmm_content
    assert "/obj/machinery/power/apc" in dmm_content
    assert "(1,1,1) = {" in dmm_content
