def get_model_config(model_name: str):
    configs = {
        "gemma-2-2b-it": {
            "num_layers": 26,
            "num_heads": 8,
            "num_kv_heads": 4,
            "hidden_size": 2048,
            "ffn_hidden_size": 16384,
            "head_dim": 256,
            "vocab_size": 256000,
            "rms_norm_eps": 1e-6,
            "rms_norm_add_unit_offset": True,
            "embed_scale": True,
            "sliding_window": 4096,
            "sliding_window_pattern": "alternating",
            "attn_logit_softcapping": 50.0,
            "final_logit_softcapping": 30.0,
            "q_chunk": 32,
            "k_chunk": 64,
        },
        "gemma-2-9b-it": {
            "num_layers": 42,
            "num_heads": 16,
            "num_kv_heads": 8,
            "hidden_size": 3584,
            "ffn_hidden_size": 14336,
            "head_dim": 256,
            "vocab_size": 256000,
            "rms_norm_eps": 1e-6,
            "rms_norm_add_unit_offset": True,
            "embed_scale": True,
            "sliding_window": 4096,
            "sliding_window_pattern": "alternating",
            "attn_logit_softcapping": 50.0,
            "final_logit_softcapping": 30.0,
            "q_chunk": 32,
            "k_chunk": 64,
        },
        "medgemma-27b": {
            "num_layers": 42,
            "num_heads": 32,
            "num_kv_heads": 16,
            "hidden_size": 4608,
            "ffn_hidden_size": 36864,
            "head_dim": 256,
            "vocab_size": 256000,
            "rms_norm_eps": 1e-6,
            "rms_norm_add_unit_offset": True,
            "embed_scale": True,
            "sliding_window": 4096,
            "sliding_window_pattern": "alternating",
            "attn_logit_softcapping": 50.0,
            "final_logit_softcapping": 30.0,
            "q_chunk": 32,
            "k_chunk": 64,
        }
    }
    if model_name not in configs:
        raise ValueError(f"Unknown model name: {model_name}")
    return configs[model_name]
