"""Web Cache Deception Defense & Content-Type Enforcer.
Resolves Issue #87: Web Cache Deception -> Session Token Leak Defense ($150).
"""

from typing import Dict, List, Optional, Set, Tuple
from urllib.parse import urlsplit


class CacheDeceptionSecurityError(ValueError):
    """Raised when URL paths or MIME types violate cache security boundaries."""
    pass


class CacheDeceptionManager:
    """Manages cache policy enforcement, strict Content-Type headers,
    and Cache-Control directives to prevent Web Cache Deception attacks.
    """

    # Static file extensions commonly targeted for cache deception
    STATIC_EXTENSIONS: Set[str] = {
        ".css", ".js", ".png", ".jpg", ".jpeg", ".gif", ".ico",
        ".svg", ".woff", ".woff2", ".ttf", ".eot", ".webp", ".mp4"
    }

    # Sensitive route prefixes that must never be cached
    SENSITIVE_PREFIXES: Tuple[str, ...] = (
        "/account",
        "/profile",
        "/settings",
        "/auth",
        "/login",
        "/api/user",
        "/api/wallet",
        "/api/session",
        "/dashboard",
        "/billing",
    )

    def __init__(
        self,
        custom_sensitive_prefixes: Optional[List[str]] = None,
        custom_static_extensions: Optional[List[str]] = None,
    ):
        if custom_sensitive_prefixes:
            self.sensitive_prefixes = tuple(p.lower().rstrip("/") for p in custom_sensitive_prefixes)
        else:
            self.sensitive_prefixes = self.SENSITIVE_PREFIXES

        if custom_static_extensions:
            self.static_extensions = {ext.lower() if ext.startswith(".") else f".{ext.lower()}" for ext in custom_static_extensions}
        else:
            self.static_extensions = self.STATIC_EXTENSIONS

    def is_sensitive_path(self, path: str) -> bool:
        """Determine if a requested URL path belongs to an authenticated/sensitive scope."""
        norm_path = (path or "").lower().strip()
        return any(norm_path == p or norm_path.startswith(f"{p}/") for p in self.sensitive_prefixes)

    def has_static_extension(self, path: str) -> bool:
        """Check if path ends with a known static file extension."""
        norm_path = (path or "").lower().strip()
        return any(norm_path.endswith(ext) for ext in self.static_extensions)

    def evaluate_response_cache_policy(
        self,
        request_path: str,
        content_type: str,
        is_authenticated: bool = False,
    ) -> Dict[str, str]:
        """Generate mandatory response headers to prevent Web Cache Deception.

        Enforces:
        1. 'X-Content-Type-Options: nosniff'
        2. 'Cache-Control: no-store, no-cache, must-revalidate, private' on sensitive/auth routes
        3. Prevention of extension-based caching on dynamic HTML/JSON endpoints.

        Args:
            request_path: The incoming request path.
            content_type: The MIME type generated by the application.
            is_authenticated: True if the request carries a valid session/auth token.

        Returns:
            Dict of HTTP response headers to apply.
        """
        headers: Dict[str, str] = {
            "X-Content-Type-Options": "nosniff",
            "Vary": "Cookie, Authorization",
        }

        clean_path = urlsplit(request_path).path.lower()
        clean_content_type = content_type.lower().split(";")[0].strip()

        # Sensitive paths or authenticated sessions must NEVER be cached by public caches/CDNs
        if is_authenticated or self.is_sensitive_path(clean_path):
            headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0, private"
            headers["Pragma"] = "no-cache"
            return headers

        # If a path carries a static file extension but the response is dynamic HTML/JSON, reject caching
        if self.has_static_extension(clean_path) and clean_content_type in ("text/html", "application/json"):
            headers["Cache-Control"] = "no-store, private"
            return headers

        # Legitimate static asset: allow caching only if Content-Type matches static asset type
        if self.has_static_extension(clean_path):
            headers["Cache-Control"] = "public, max-age=86400, immutable"
        else:
            headers["Cache-Control"] = "no-cache, private"

        return headers

    def should_cdn_cache(
        self,
        request_path: str,
        response_headers: Dict[str, str],
    ) -> bool:
        """CDN decision rule: cache decisions must be based on actual response Content-Type
        and explicit Cache-Control headers, NEVER solely on the URL extension.

        Returns:
            bool: True if the response is safe to cache on CDN edge nodes.
        """
        header_map = {k.lower(): v.lower() for k, v in response_headers.items()}
        cache_control = header_map.get("cache-control", "")

        # Explicit prohibition
        if "no-store" in cache_control or "private" in cache_control:
            return False

        content_type = header_map.get("content-type", "").split(";")[0].strip()

        # Dynamic documents (HTML, JSON) must never be cached merely because of a URL extension trick
        if content_type in ("text/html", "application/json", "application/xml"):
            return False

        # Must have public cache directive
        if "public" not in cache_control:
            return False

        return True
