#!/usr/bin/env python3
"""
评分系统 — Scoring System
提交代码质量评分，百分制，≥90 分达标。

评分维度:
  - 功能正确性 (40分) — pytest 通过率
  - 安全性     (35分) — 作弊检测+静态分析
  - 代码质量   (15分) — pylint + 圈复杂度
  - 性能       (10分) — 执行效率

一票否决项（0分）:
  - AST 检测到直接返回预期输出
  - 删除/篡改测试用例
  - 引入外部恶意依赖
  - 代码为空/乱码
  - bandit 检测到高危漏洞
  - 检测到自动提交机器人特征
  - 检测到重复提交/批量提交行为

用法:
    python scripts/score.py --code <file> --tests <test_dir>
    python scripts/score.py --check <file>   # 仅检查作弊
"""

import argparse
import ast
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path


# ── 评分配置 ─────────────────────────────────────────────────────

PASS_THRESHOLD = 90
WEIGHTS = {
    "correctness": 40,
    "security": 35,
    "quality": 15,
    "performance": 10,
}

# 已知自动提交机器人的特征模式
BOT_SIGNATURES = [
    r"talos[-_]agent",
    r"github[-_]bounty[-_]scout",
    r"auto[-_]submit",
    r"bounty[-_]hunter[-_]bot",
    r"opire[-_]bot",
    r"algora[-_]bot",
    r"pm2[-_]service",
    r"autonomous[-_]agent",
    r"agentic[-_]submit",
]

# 可疑的自动生成代码特征
AUTO_GENERATED_PATTERNS = [
    r"#\s*AUTO[-_]GENERATED",
    r"#\s*Generated by",
    r"#\s*This file was automatically",
    r"talos[-_]watcher",
    r"bounty[-_]scout",
]


# ── 反作弊检测 ────────────────────────────────────────────────────

def check_bot_submission(code: str, metadata: dict = None) -> list[str]:
    """
    检测自动化机器人提交特征。
    
    Anti-cheat: Detects automated bot submissions from services like
    talos-agent, github-bounty-scout, and similar autonomous systems
    that attempt to game the bounty system.
    """
    violations = []
    
    # 检查代码中的机器人签名
    code_lower = code.lower()
    for pattern in BOT_SIGNATURES:
        if re.search(pattern, code_lower, re.IGNORECASE):
            violations.append(f"[反作弊] 检测到自动化机器人签名: {pattern}")
    
    # 检查自动生成代码特征
    for pattern in AUTO_GENERATED_PATTERNS:
        if re.search(pattern, code, re.IGNORECASE):
            violations.append(f"[反作弊] 检测到自动生成代码特征: {pattern}")
    
    # 检查元数据中的机器人特征
    if metadata:
        submitter = str(metadata.get("submitter", "")).lower()
        submitter_type = str(metadata.get("submitter_type", "")).lower()
        
        bot_keywords = ["bot", "agent", "auto", "talos", "scout", "autonomous", "agentic"]
        for kw in bot_keywords:
            if kw in submitter or kw in submitter_type:
                violations.append(f"[反作弊] 提交者特征疑似机器人: submitter={submitter}")
                break
    
    return violations


def check_duplicate_submission(submission_id: str, results_dir: str) -> list[str]:
    """
    检测重复提交或批量提交行为。
    
    Anti-cheat: Prevents the same entity from submitting multiple times
    to game the scoring system.
    """
    violations = []
    
    if not results_dir or not os.path.isdir(results_dir):
        return violations
    
    if not submission_id:
        return violations
    
    # 提取提交者标识（去掉时间戳等唯一部分）
    # 格式通常为: username_timestamp 或 username_hash
    parts = submission_id.rsplit("_", 1)
    if len(parts) < 2:
        return violations
    
    base_submitter = parts[0]
    
    # 统计同一提交者在短时间内的提交次数
    submission_times = []
    for fname in os.listdir(results_dir):
        if not fname.endswith("_result.json"):
            continue
        if fname.startswith(base_submitter):
            fpath = os.path.join(results_dir, fname)
            try:
                mtime = os.path.getmtime(fpath)
                submission_times.append(mtime)
            except OSError:
                pass
    
    # 如果同一提交者在1小时内提交超过5次，视为批量提交
    if len(submission_times) > 5:
        now = time.time()
        recent = [t for t in submission_times if now - t < 3600]
        if len(recent) > 5:
            violations.append(f"[反作弊] 检测到批量提交行为: {base_submitter} 在1小时内提交 {len(recent)} 次")
    
    return violations


def check_ast_cheating(code: str) -> list[str]:
    """AST 静态分析检测作弊行为"""
    violations = []
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        violations.append(f"代码语法错误: {e}")
        return violations

    for node in ast.walk(tree):
        # 检测直接 return 硬编码值
        if isinstance(node, ast.FunctionDef):
            for n in ast.walk(node):
                if isinstance(n, ast.Return) and isinstance(n.value, (ast.Constant, ast.List, ast.Dict)):
                    if isinstance(n.value, ast.Constant) and isinstance(n.value.value, str) and len(n.value.value) > 20:
                        violations.append(f"函数 {node.name} 直接返回硬编码字符串（疑似预期输出伪造）")
                        break
                    if isinstance(n.value, ast.List) and len(n.value.elts) > 2:
                        violations.append(f"函数 {node.name} 直接返回硬编码列表（疑似预期输出伪造）")
                        break

        # 检测 eval/exec
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name) and node.func.id in ("eval", "exec", "compile"):
                violations.append(f"禁止使用 {node.func.id}()")
            if isinstance(node.func, ast.Attribute):
                if node.func.attr in ("system", "popen", "call", "run") and isinstance(node.func.value, ast.Name) and node.func.value.id in ("os", "subprocess"):
                    if True:  # 所有危险系统调用
                        violations.append(f"危险系统调用: {node.func.value.id}.{node.func.attr}()")

        # 检测 import 白名单违规
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                module = alias.name.split(".")[0]
                if module in ("pickle", "marshal", "shelve", "ctypes", "imp", "importlib"):
                    violations.append(f"禁止使用模块: {module}")

    return violations


def check_bandit(code_file: str) -> list[str]:
    """调用 bandit 做安全扫描"""
    violations = []
    try:
        result = subprocess.run(
            ["bandit", "-q", "-f", "json", code_file],
            capture_output=True, text=True, timeout=30
        )
        if result.stdout:
            data = json.loads(result.stdout)
            for issue in data.get("results", []):
                if issue.get("issue_severity") in ("HIGH", "MEDIUM"):
                    violations.append(f"[bandit] {issue.get('test_name')}: {issue.get('issue_text')}")
    except (FileNotFoundError, subprocess.TimeoutExpired, json.JSONDecodeError):
        violations.append("[安全扫描] bandit 未安装或执行失败，无法评分")
    return violations


def check_test_tampering(original_hash: str, test_dir: str) -> list[str]:
    """检查测试用例是否被篡改"""
    violations = []
    if not original_hash:
        return violations
    for f in Path(test_dir).glob("test_*.py"):
        content = f.read_text()
        current_hash = hashlib.md5(content.encode()).hexdigest()[:16]
        # 简单校验：文件行数
        with open(f) as fh:
            lines = len(fh.readlines())
        if lines < 3:
            violations.append(f"测试文件 {f.name} 被清空或篡改")
    return violations


def check_submission_integrity(code: str, submission_id: str = None, 
                                results_dir: str = None, metadata: dict = None) -> list[str]:
    """
    综合反作弊完整性检查。
    
    Anti-cheat entry point that combines all detection methods:
    1. Bot signature detection
    2. Duplicate/bulk submission detection  
    3. AST-based hardcoded output detection
    4. Code emptiness/gibberish detection
    """
    all_violations = []
    
    # 1. 检查机器人提交特征
    bot_violations = check_bot_submission(code, metadata)
    all_violations.extend(bot_violations)
    
    # 2. 检查重复提交
    if submission_id and results_dir:
        dup_violations = check_duplicate_submission(submission_id, results_dir)
        all_violations.extend(dup_violations)
    
    # 3. 检查代码是否为空或乱码
    stripped = code.strip()
    if len(stripped) < 10:
        all_violations.append("[反作弊] 代码为空或过短")
    
    # 4. 检查是否为纯随机乱码（熵值检测）
    if stripped and len(stripped) > 0:
        # 计算可打印字符比例
        printable = sum(1 for c in stripped if c.isprintable())
        ratio = printable / len(stripped)
        if ratio < 0.7:
            all_violations.append("[反作弊] 代码包含大量不可打印字符（疑似乱码）")
    
    return all_violations


# ── 评分函数 ─────────────────────────────────────────────────────

def score_correctness(test_dir: str) -> tuple:
    """运行 pytest，返回 (分数, 详情)"""
    if not test_dir or not os.path.isdir(test_dir):
        return 0, "无测试目录"
    try:
        result = subprocess.run(
            ["python", "-m", "pytest", test_dir, "-v", "--tb=short", ],
            capture_output=True, text=True, timeout=120
        )
        # 从 stdout 解析测试结果
        passed = result.stdout.count("PASSED")
        failed = result.stdout.count("FAILED") + result.stdout.count("ERROR") + result.stdout.count("ERRORS")
        total = passed + failed
        if total == 0:
            return 0, "无测试用例"
        rate = passed / total if total > 0 else 0
        score = round(40 * rate)
        return score, f"{passed}/{total} 通过"
    except (FileNotFoundError, subprocess.TimeoutExpired) as e:
        return 0, f"测试执行失败: {e}"


def score_security(violations: list[str], code: str) -> tuple:
    """安全评分，满分 35，每项违规扣 7 分"""
    deductions = min(len(violations) * 7, 35)
    score = 35 - deductions
    detail = f"{len(violations)} 项违规" if violations else "无违规"
    return max(0, score), detail


def score_quality(code_file: str) -> tuple:
    """代码质量评分，满分 15"""
    if not code_file or not os.path.isfile(code_file):
        return 0, "无代码文件"
    try:
        result = subprocess.run(
            ["pylint", code_file, "--score=y", "-f", "text"],
            capture_output=True, text=True, timeout=60
        )
        # 提取 pylint 分数
        match = re.search(r"Your code has been rated at ([\d.]+)/10", result.stdout)
        if match:
            pylint_score = float(match.group(1))
            score = round(15 * pylint_score / 10)
            return score, f"pylint: {pylint_score}/10"
        return 7, "pylint 评分解析失败，给予默认分"
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return 7, "pylint 未安装，给予默认分"


def score_performance(code_file: str, test_dir: str) -> tuple:
    """性能评分，满分 10"""
    if not code_file or not test_dir:
        return 5, "无法评估性能，给予默认分"
    
    try:
        start = time.time()
        result = subprocess.run(
            ["python", "-m", "pytest", test_dir, "-q", "--tb=no"],
            capture_output=True, text=True, timeout=60
        )
        elapsed = time.time() - start
        
        # 基于执行时间评分
        if elapsed < 5:
            return 10, f"执行时间: {elapsed:.2f}s (优秀)"
        elif elapsed < 15:
            return 8, f"执行时间: {elapsed:.2f}s (良好)"
        elif elapsed < 30:
            return 5, f"执行时间: {elapsed:.2f}s (一般)"
        else:
            return 2, f"执行时间: {elapsed:.2f}s (较慢)"
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return 5, "性能测试超时或失败，给予默认分"


# ── 主评分流程 ─────────────────────────────────────────────────────

def score_submission(code_file: str, test_dir: str = None, 
                     submission_id: str = None, results_dir: str = None,
                     metadata: dict = None) -> dict:
    """
    完整评分流程，返回评分结果字典。
    包含反作弊检测。
    """
    if not os.path.isfile(code_file):
        return {
            "total_score": 0,
            "passed": False,
            "disqualified": True,
            "reason": f"代码文件不存在: {code_file}",
            "details": {}
        }
    
    with open(code_file, encoding="utf-8", errors="replace") as f:
        code = f.read()
    
    # ── 反作弊检查（一票否决）──
    integrity_violations = check_submission_integrity(
        code, submission_id, results_dir, metadata
    )
    ast_violations = check_ast_cheating(code)
    bandit_violations = check_bandit(code_file)
    
    all_violations = integrity_violations + ast_violations + bandit_violations
    
    # 一票否决：任何严重违规直接0分
    veto_violations = [v for v in all_violations if any(kw in v for kw in [
        "反作弊", "禁止使用", "危险系统调用", "语法错误", "乱码", "为空"
    ])]
    
    if veto_violations:
        return {
            "total_score": 0,
            "passed": False,
            "disqualified": True,
            "reason": "一票否决: " + "; ".join(veto_violations[:3]),
            "violations": all_violations,
            "details": {
                "correctness": {"score": 0, "detail": "因违规取消资格"},
                "security": {"score": 0, "detail": "; ".join(veto_violations[:3])},
                "quality": {"score": 0, "detail": "因违规取消资格"},
                "performance": {"score": 0, "detail": "因违规取消资格"},
            }
        }
    
    # ── 正常评分流程 ──
    correctness_score, correctness_detail = score_correctness(test_dir)
    security_score, security_detail = score_security(all_violations, code)
    quality_score, quality_detail = score_quality(code_file)
    performance_score, performance_detail = score_performance(code_file, test_dir)
    
    total = correctness_score + security_score + quality_score + performance_score
    total = max(0, min(100, total))
    
    return {
        "total_score": total,
        "passed": total >= PASS_THRESHOLD,
        "disqualified": False,
        "violations": all_violations,
        "details": {
            "correctness": {"score": correctness_score, "detail": correctness_detail},
            "security": {"score": security_score, "detail": security_detail},
            "quality": {"score": quality_score, "detail": quality_detail},
            "performance": {"score": performance_score, "detail": performance_detail},
        }
    }


def main():
    parser = argparse.ArgumentParser(description="Score a submission")
    parser.add_argument("--code", required=False, help="Code file to score")
    parser.add_argument("--tests", default=None, help="Test directory")
    parser.add_argument("--check", default=None, help="Only run anti-cheat check on file")
    parser.add_argument("--submission-id", default=None, help="Submission ID for duplicate detection")
    parser.add_argument("--results-dir", default=None, help="Results directory for duplicate detection")
    parser.add_argument("--metadata", default=None, help="JSON metadata string")
    parser.add_argument("--json", action="store_true", help="JSON output")
    args = parser.parse_args()

    # 仅作弊检查模式
    if args.check:
        if not os.path.isfile(args.check):
            print(f"文件不存在: {args.check}", file=sys.stderr)
            return 1
        with open(args.check, encoding="utf-8", errors="replace") as f:
            code = f.read()
        
        metadata = None
        if args.metadata:
            try:
                metadata = json.loads(args.metadata)
            except json.JSONDecodeError:
                pass
        
        violations = check_submission_integrity(code, args.submission_id, args.results_dir, metadata)
        violations += check_ast_cheating(code)
        violations += check_bandit(args.check)
        
        if args.json:
            print(json.dumps({"violations": violations, "clean": len(violations) == 0}, 
                           indent=2, ensure_ascii=False))
        else:
            if violations:
                print(f"❌ 发现 {len(violations)} 项违规:")
                for v in violations:
                    print(f"  - {v}")
            else:
                print("✅ 未发现违规")
        return 1 if violations else 0

    if not args.code:
        parser.print_help()
        return 1

    metadata = None
    if args.metadata:
        try:
            metadata = json.loads(args.metadata)
        except json.JSONDecodeError:
            pass

    result = score_submission(
        args.code, args.tests,
        submission_id=args.submission_id,
        results_dir=args.results_dir,
        metadata=metadata
    )

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print(f"总分: {result['total_score']}/100")
        print(f"达标: {'✅' if result['passed'] else '❌'}")
        if result.get("disqualified"):
            print(f"取消资格: {result.get('reason', '')}")
        if result.get("violations"):
            print(f"违规项 ({len(result['violations'])}):")
            for v in result["violations"]:
                print(f"  - {v}")
        print("\n详细评分:")
        for dim, info in result.get("details", {}).items():
            print(f"  {dim}: {info['score']} 分 — {info['detail']}")

    return 0 if result["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())