name: Auto Redeem
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_num:
        description: "Issue number"
        required: true
        default: "11"
jobs:
  redeem:
    if: github.event_name == 'issue_comment' && contains(github.event.issue.labels.*.name, 'redeem') && contains(github.event.comment.body, '/redeem')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Init DB
        run: python scripts/coin.py balance admin --init
      - name: Approve
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUM: ${{ github.event.issue.number }}
        run: python scripts/redeem_issue.py
