"""Data models and transfer objects for Bedrock build pipeline."""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass(frozen=True)
class SoundDefinitionEntry:
    """Represents a Bedrock sound definition event entry.

    Attributes:
        category: Sound category (e.g. player, block, ambient).
        sounds: List of relative audio file resource identifiers.
        volume: Playback volume multiplier.
        pitch: Playback pitch multiplier.
    """

    category: str
    sounds: List[str]
    volume: float = 1.0
    pitch: float = 1.0


@dataclass(frozen=True)
class CompilationResult:
    """Result of compiling a single template or asset file.

    Attributes:
        source_path: Path to the source file.
        destination_path: Path where compiled output was written.
        success: Whether compilation succeeded.
        from_cache: Whether compilation was skipped due to clean cache hit.
        error: Error message if compilation failed.
        expanded_directives: Number of template directives processed.
        duration_ms: Processing duration in milliseconds.
    """

    source_path: str
    destination_path: str
    success: bool
    from_cache: bool = False
    error: Optional[str] = None
    expanded_directives: int = 0
    duration_ms: float = 0.0


@dataclass
class BuildStats:
    """Summary statistics for a build pipeline execution.

    Attributes:
        total_files: Total candidate files examined.
        compiled_templates: Number of JsonTE templates expanded.
        compiled_audio: Number of sound assets aggregated into definitions.
        passthrough_files: Number of static files copied unmodified.
        cached_files: Number of unchanged files skipped via cache.
        failed_files: Number of files that encountered errors.
        duration_seconds: Total pipeline wall-clock time in seconds.
    """

    total_files: int = 0
    compiled_templates: int = 0
    compiled_audio: int = 0
    passthrough_files: int = 0
    cached_files: int = 0
    failed_files: int = 0
    duration_seconds: float = 0.0


@dataclass(frozen=True)
class ValidationReport:
    """Report generated by deployment integrity validator.

    Attributes:
        is_valid: Whether all validation assertions passed.
        checked_files: Total output files analyzed in target directory.
        source_unmodified: Whether source files were verified strictly unmodified.
        json_valid: Whether all output JSON files conform to Bedrock schema.
        directives_cleared: Whether zero unexpanded template syntax remained.
        errors: Detailed list of validation failure descriptions.
    """

    is_valid: bool
    checked_files: int
    source_unmodified: bool
    json_valid: bool
    directives_cleared: bool
    errors: List[str] = field(default_factory=list)
